name: weather-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy
  - pandas
  - xarray
  - netcdf4
  - matplotlib
  - scikit-image
  - tqdm
  - requests
  - beautifulsoup4
  - geopandas
  - shapely
  - cartopy
  - gdal
  - pyogrio
  - cfgrib
  - eccodes
  - rioxarray
  - rasterio
  - pyproj
  - ipython
  - pillow
  - pip
  - pip:
      - PyGithub
      - python-awips
