name: weather-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy
  - pandas
  - xarray
  - netcdf4
  - matplotlib
  - scikit-image
  - tqdm
  - requests
  - beautifulsoup4
  - geopandas
  - shapely
  - cartopy
  - gdal=3.7
  - pyogrio
  - cfgrib
  - eccodes
  - rioxarray
  - ipython
  - pyqt=5
  - pyqtwebengine
  - pip
  - pip:
      - PyGithub
      - sendgrid
      - python-awips
